apiVersion: v1
kind: Service
metadata:
  name: { { .Values.client.name } }
spec:
  selector:
    app: client
  type: { { .Values.client.type } }
  ports:
    - protocol: TCP
      port: { { .Values.client.port } }
      targetPort: { { .Values.client.port } }
