apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: { { .Values.server.replicas } }
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: { { .Values.server.image.repository } }
          env:
            - name: PORT
              value: { { .Values.server.port } }
