apiVersion: v1
kind: Service
metadata:
  name: { { .Values.server.name } }
spec:
  selector:
    app: server
  type: { { .Values.server.type } }
  ports:
    - protocol: TCP
      port: { { .Values.server.port } }
      targetPort: { { .Values.server.port } }
